version: '3'

services:
  mock-backend-subsistema-1:
    image: javieryz/mock-backend-subsistema-1
    container_name: aos2023_mock_subsistema_1
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4011:4010"

  frontend-subsistema-1:
    image: javieryz/frontend-subsistema-1
    container_name: aos2023_ui_subsistema_1
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  mock-backend-subsistema-2:
    image: javieryz/mock-backend-subsistema-2
    container_name: aos2023_mock_subsistema_2
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4012:4010"

  frontend-subsistema-2:
    image: javieryz/frontend-subsistema-2
    container_name: aos2023Trabajos_ui
    ports:
      - "8002:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  mock-backend-subsistema-3:
    image: javieryz/mock-backend-subsistema-3
    container_name: aos2023_mock_subsistema_3
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4013:4010"

  frontend-subsistema-3:
    image: javieryz/frontend-subsistema-3
    container_name: aos2023_ui_subsistema_3
    ports:
      - "8003:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  subsistema-4:
    image: javieryz/notificaciones:latest
    container_name: aos2023_subsistema_4
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "4014:8000"
    depends_on:
      - db-subsistema-4
  
  db-subsistema-4:
    image: javieryz/db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=aos2023
    ports:
      - "3306:3306"

  frontend-subsistema-4:
    image: javieryz/frontend-subsistema-4
    container_name: aos2023_ui_subsistema_4
    ports:
      - "8004:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  mock-backend-subsistema-5:
    image: javieryz/mock-backend-subsistema-5
    container_name: aos2023_mock_subsistema_5
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4015:4010"

  frontend-subsistema-5:
    image: javieryz/frontend-subsistema-5
    container_name: aos2023_ui_subsistema_5
    ports:
      - "8005:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  mock-backend-subsistema-6:
    image: javieryz/mock-backend-subsistema-6
    container_name: aos2023_mock_subsistema_6
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4016:4010"

  frontend-subsistema-6:
    image: javieryz/frontend-subsistema-6
    container_name: aos2023_ui_subsistema_6
    ports:
      - "8006:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml

  mock-backend-subsistema-7:
    image: javieryz/mock-backend-subsistema-7
    container_name: aos2023_mock_subsistema_7
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4017:4010"

  frontend-subsistema-7:
    image: javieryz/frontend-subsistema-7
    container_name: aos2023_ui_subsistema_7
    ports:
      - "8007:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml